POST http://localhost:3000/cwags

###
PUT  http://localhost:3000/cwags/628d220ad047ceb72a287d05 HTTP/1.1
# # Content-Type: application/json

# # {     

#     "styleName": "Bold",
#     "styleImages": "#",
#     "styleDescription": "regular",
#     "styleColor": "grey",
#     "modelDescription": "muscular",
#     "stylePrice": "$50",
#     "styleDetails": "In demand",
#     "quantiy": "20",
# #     

# #     }


###

DELETE http://localhost:3000/cwags/628d220ad047ceb72a287d05 HTTP/1.1


###

POST http://localhost:3000/cwags HTTP/1.1
content-type: application/json

{
  "styleName": "any",
  "styleImages": "any",
  "styleDescription": "any",
  "styleColor": "any",
  "modelDescription": "any",
  "stylePrice": "any",
  "styleDetails": "any",
  "quantiy": "99"
}


###
PUT  http://localhost:3000/cwags/629e630c17008e76cdab2ef9 HTTP/1.1

###
DELETE http://localhost:3000/cwags/629e630c17008e76cdab2ef9 HTTP/1.1
